feat: add kubernetes_api_service for new pipeline
lenra-io/server pull request #360
Opened 2023-03-03 08:52 UTC by shiipou

Signed-off-by: shiipou <shiishii@nocturlab.fr>
Closes #340 

## Checklist
- [x] I didn't over-scope my PR
- [x] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [x] I added/updated the documentation about my changes
- [x] I made my own code-review before requesting one

## Description of the changes

## Technical highlight/advice

2023-03-10 14:24 UTC, taorepoara approved these changes
Seems OK

@pichoemr Can you look at it two please

2023-03-10 14:24 UTC, taorepoara commented
@shiipou You have a formating issue in the CI

2023-03-10 14:35 UTC, taorepoara commented on apps/lenra/lib/lenra/services/kubernetes_api_services.ex
> +        spec: %{
The job does not have resources management

2023-03-14 12:40 UTC, pichoemr requested changes

2023-03-14 12:40 UTC, pichoemr commented on apps/lenra/lib/lenra/apps.ex
> +          _ -> BusinessError.pipeline_runner_unkown_service()
You should return a tuple `{:error, <error>}` inside a run:

```suggestion
          _ -> BusinessError.pipeline_runner_unkown_service_tuple()
```

2023-03-14 12:40 UTC, pichoemr commented on config/releases.exs
> +  kubernetes_api_url: System.get_env("KUBERNETES_API_URL") || "https://#{System.get_env("KUBERNETES_SERVICE_HOST")}",
In the case KUBERNETES_API_URL & KUBERNETES_SERVICE_HOST are not set you will have an url: `"https://"`. Maybe only let KUBERNETES_API_URL with `fetch_env!`

2023-04-25 13:38 UTC, shiipou reviewed
fix: use fetch_env to not allow empty var `KUBERNETES_SERVICE_HOST` if `KUBERNETES_API_URL` is not defined

2023-05-10 11:56 UTC, pichoemr requested changes

2023-05-10 11:56 UTC, pichoemr commented on apps/lenra/lib/lenra/services/kubernetes_api_services.ex
> +                "memory":"100Mi"
Missing spaces after `:` that cause compile error
```suggestion
                "cpu": "500m",
                "memory": "1024Mi"
              },
              "requests": %{
                "cpu": "50m",
                "memory": "100Mi"
```

2023-05-24 07:22 UTC, pichoemr approved these changes
Fix CI with a `mix format` and it's good for me

2023-06-06 15:38 UTC, pichoemr requested changes

2023-06-08 13:16 UTC, shiipou commented on config/dev.exs
> +  pipeline_runner: System.get_env("PIPELINE_RUNNER", "GitLab"),
Why that ?
GitLab or gitlab or gitLab is the same because the check does a toLowerCase in the code.

2023-07-11 08:53 UTC, shiipou commented
I need to document this addition.

2023-08-04 11:47 UTC, taorepoara requested changes

2023-08-04 11:47 UTC, taorepoara commented on docs/env-variables.md
> +- `APP_HOST`: The host of the application.
```suggestion
- `APP_HOST`: The host of the API. This variable should change in the futur.
```

2023-08-04 12:08 UTC, taorepoara approved these changes
Seems OK

2023-08-04 12:13 UTC, shiipou commented on docs/env-variables.md
> +
```suggestion
```

2023-08-04 12:13 UTC, merged

2023-08-22 11:22 UTC, taorepoara commented
:tada: This PR is included in version 1.0.0-alpha.6 :tada:

The release is available on:
- [GitHub release](https://github.com/lenra-io/server/releases/tag/v1.0.0-alpha.6)
- `v1.0.0-alpha.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-10-07 23:42 UTC, taorepoara commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/lenra-io/server/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: