Consent page design
lenra-io/server pull request #402
Opened 2023-08-09 10:17 UTC by taorepoara

Closes #389 

## Description of the changes
Implements the consent page design.

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I made my own code-review before requesting one

### I included unit tests that cover my changes
  - [ ] 👍 yes
  - [ ] 🙅 no, because they aren't needed
  - [ ] 🙋 no, because I need help

### I added/updated the documentation about my changes

- [ ] 📜 README.md
- [ ] 📕 docs/*.md
- [ ] 📓 docs.lenra.io
- [ ] 🙅 no documentation needed

2023-08-17 12:54 UTC, jonas-martinez commented
It seems that the app name is not shown on the consent page. Is it a problem on my side or on your side ?

<img width="481" alt="image" src="https://github.com/lenra-io/server/assets/36544012/a46792ac-406a-4b91-bfc8-77294de04518">

2023-08-17 12:55 UTC, jonas-martinez requested changes
See my comment above

2023-08-18 11:24 UTC, taorepoara commented
@jonas-martinez How did you create the OAuth client ?

Did you use the dedicated Elixir task ?

2023-08-18 11:34 UTC, jonas-martinez commented
No, it was why it did not show the app name on the screen. It works now :smiley:

2023-08-18 11:34 UTC, jonas-martinez approved these changes

2023-08-18 12:28 UTC, jonas-martinez requested changes

2023-08-18 12:28 UTC, jonas-martinez commented on apps/identity_web/lib/identity_web/templates/user_consent/consent.html.heex
> +    <p><%= raw(gettext("<strong>%{app_name}</strong> is requesting access to your Lenra’s account.", app_name: get_client_name(@client))) %></p>
```suggestion
    <p><%= raw(gettext("<strong>%{app_name}</strong> is requesting access to your Lenra account.", app_name: get_client_name(@client))) %></p>
```

2023-08-18 12:32 UTC, jonas-martinez approved these changes

2023-08-18 12:37 UTC, merged